services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
    networks: 
      - network-callisto
    
  callisto:
    build:
      context: .
      dockerfile: Dockerfile.callisto
      args:
        GH_TOKEN: ${GH_TOKEN}
    restart: always
    volumes:
      - callisto:/callisto/.callisto
    env_file:
      - .env
    networks: 
      - network-callisto
    depends_on:
      - postgres
  
  hasura:
    image: hasura/graphql-engine:v2.45.0-beta.1-ce.ubuntu
    ports:
      - "8080:8080"
      - "3000:3000"
    restart: always
    environment:
      ACTION_BASE_URL: "http://callisto:3000"
    env_file:
      - .env
    networks: 
      - network-callisto
    depends_on:
      - postgres
      - callisto

networks:
  network-callisto:

volumes:
  callisto:
  postgres:
